### ISSUE TITLE
ViT-B weights finetuned on FunnyBirds 

### ISSUE THREAD

**Issue by LokeshBadisa** [visinf/funnybirds-framework#2]
Very helpful work for XAI community!!

I see that you have also compared transformer explainability methods with FunnyBirds framework in paper. However, the `README` shows I can only download the resnet50 and VGG16 models' weights finetuned on FunnyBirds. Can you open-source ViT's model's weights which is finetuned on FunnyBirds? If it is already available publicly, please point me to it.

**Comment by robinhesse** [comment]
Hi,

Thank you very much for your interest in our work! I have added the code + weights for ViT. Please let me know if anything is not working as expected.

Best,
Robin
