### ISSUE TITLE
Unnecessary Riemann Sum?

### ISSUE THREAD

**Issue by LokeshBadisa** [visinf/funnybirds-framework#4]
In the below code, it seems like you are calculating riemann sum but not using it anywhere. Is it mis-placed or is it part of pre-publication code which didn't work out?

https://github.com/visinf/funnybirds-framework/blob/aa9e9f47b821a1da046b0a9b2acae57d45a08407/evaluation_protocols.py#L345-L350

**Comment by robinhesse** [comment]
Hi,

This is just some pre-publication code that did not make it in the final paper. Thanks for letting me know! I have deleted it.

Best,
Robin
